# Generated by Django 5.0.3 on 2024-03-27 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_posts",
                through="twitterapp.Like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
