# Generated by Django 5.0.3 on 2024-03-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp", "0003_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
